### ISSUE TITLE
Can't get quiz which created by other user

### ISSUE THREAD

**Issue by ZengXianhan** [ISSSE31PTDMSSGroup4/msegroups-quiz-service#6]
When call GetQuizDetail API
If the X-USER does not match the quiz creator, it will report 400 errors.
But there is a case for another user to fetch the quiz details to join the quiz.

So could you please release the X-USER constraint to allow other users to get the quiz details?

**Comment by ZengXianhan** [comment]
My test case:
quiz_id = c33e8797 
creator = user1

if call from user1 => return 200
if call from user2 => return 400

**Comment by shajini0909** [comment]
Have updated, please help to verify it's as expected 🙂 

Also, added a check so that if (it ever happens) there are multiple quizzes with the same ID, it will return 400 saying "quiz has duplicate records"

**Comment by ZengXianhan** [comment]
Tested, right now user2 can access the quiz detail which created by user1, thank you.

if call from user1 => return 200
if call from user2 => return 200
